sudo: required
os: linux
dist: xenial
language: node_js
node_js:
- lts/*
env:
  global:
  - BUILD_VERSION=0.04
  - CCACHE_SIZE=100M
  - CCACHE_TEMPDIR=/tmp/.ccache-temp
  - CCACHE_COMPRESS=1
cache:
  apt: true
  directories:
  - "$HOME/google-cloud-sdk/"
  - "$HOME/.ccache"
matrix:
  fast_finish: true
  include:
  - env: BUILD_ICONS=assets/icons/agama_icons/128x128.png IGNORE_OS_ASSETS_1=assets/bin/osx
      IGNORE_OS_ASSETS_2=assets/bin/win64 TARGET_PLATFORM=linux APP_NAME=Agama-Linux.tar.gz
      ASSETS_DIR=linux64 KOMODO_VARIANT=Linux64
  - env: BUILD_ICONS=assets/icons/agama_icons/agama_app_icon.ico IGNORE_OS_ASSETS_1=assets/bin/osx
      IGNORE_OS_ASSETS_2=assets/bin/linux64 TARGET_PLATFORM=win32 APP_NAME=Agama-Win.zip
      PACKAGES=winehq-devel ASSETS_DIR=win64 KOMODO_VARIANT=Win64
install:
- gcloud auth activate-service-account --key-file AUTH_KEY.json
- rm AUTH_KEY.json && rm AUTH_KEY.json.enc
script:
- yarn install && yarn add webpack webpack-dashboard
- cd react && yarn install && yarn run build
after_script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then cd ../.. && tar -czf $PROJECT.tar.gz $PROJECT && gsutil
  cp $PROJECT.tar.gz gs://$BUCKET/$PROJECT/$TRAVIS_BRANCH/; fi
before_install:
- openssl aes-256-cbc -K $encrypted_6b9be889f511_key -iv $encrypted_6b9be889f511_iv
  -in AUTH_KEY.json.enc -out AUTH_KEY.json -d
